name: Update CONTRIBUTORS.md
permissions: { actions: write }
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: minicli/action-contributors@v3.3
        name: "Update CONTRIBUTORS.md file"
        env:
          CONTRIB_REPOSITORY: "https://github.com/Terabit-Desktop/tb_app"
          CONTRIB_OUTPUT_FILE: "CONTRIBUTORS.md"
      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: "CONTRIBUTORS.md"
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
